### ISSUE TITLE
관리자-회원관리 디자인

### ISSUE THREAD

**Issue by sypark132** [MinJeung-Kim/Team-Project#11]
#### 1차
<img width="50%" height="50%" alt="csdesign" src="https://user-images.githubusercontent.com/79883783/111024176-97785e00-8420-11eb-9828-0a85764f5f74.PNG">

#### 2차
<img width="50%" height="50%" alt="csdesign" src="https://user-images.githubusercontent.com/79883783/111023852-ae1db580-841e-11eb-9e94-e56cb8842d86.png">

- [x] 회원 검색창
- [x] 회원 목록
- [x] 비회원 검색 추가
 1. 회원 검색창에서 아이디, 등급, 전화번호, 주문번호(비회원 검색 가능)로 검색할 수 있도록 디자인 예정
  + 회원 검색창에서 이름, 아이디, 등급으로 검색하고 비회원 검색창에서는 주문번호로 검색 가능할 수 있게 디자인했습니다.
- [x] 회원 목록
 1. 등급, 회원유형(회원/비회원), 체크박스 컬럼 추가 예정
 2. 회원 등록, 수정 버튼 추가 예정
 + 위 언급한 부분 추가 완료했고 관련 내역 보기의 '주문'은 삭제했습니다.
- [x] 하단에 페이지 번호 추가
- [ ] 관련 내역 보기
 1. 상세보기 팝업창 디자인 예정

관리자 페이지에서 푸터부분은 중요하지 않은 것 같아서 일단 삭제했습니다. 필요하면 추가하겠습니다!!
화면 배치하면서 고민이 많았습니다ㅠㅠ 더 좋은 의견이 있다면 언제든 말씀부탁드립니다!

**Comment by sypark132** [comment]
> ## 1차 디자인입니다.
> <img alt="csdesign" width="50%" height="50%" src="https://user-images.githubusercontent.com/79883783/110961747-7b7aab00-8393-11eb-8b13-ce0e31372e50.PNG">
> 
> * [x]  회원 검색창
> * [x]  회원 목록
> * [ ]   회원 검색 필터 추가
> 
> * 회원 검색창에서 아이디, 등급, 전화번호, 주문번호(비회원 검색 가능)로 검색할 수 있도록 구현
> 
> * [ ]  회원 목록
> 
> * 컬럼 추가 : 등급, 회원유형(회원/비회원), 체크박스
> * 회원 등록, 수정 버튼 추가
> 
> * [ ]  관련 내역 보기 - 주문, 전체보기 팝업창
> * [ ]  하단에 페이지 번호 추가

**Comment by MinJeung-Kim** [comment]
1. 상세보기 버튼이 따로 있기보다는 이름을 클릭하면 팝업창으로 상세보기를 띄어주는건 어떨까요 ~? 
2. 검색창을 2개로 따로 분리하는것보다 1개로 하고 ```select``` 태그로 회원, 비회원을 선택하는게 좋을거 같아요 !
3. 리스트 부분 아래에 등급관련 공지나 글씨를 써놓으면 어떨까요 ~?
- 예를 들면 VVIP : 총 주문 금액 1,000,000원 이상이고 000이상인 회원,
                   COLD : 총 주문 금액 900,000원 이상이고 000이상인 회원

이런식으로 적어두면 고객 응대에 도움이 될 것 같고 미관상 여백이 채워져서 좋을 것 같습니다 😊

**Comment by tiaz0128** [comment]
- 회원 가입 페이지에서 어떠한 정보를 입력하면서 가입하는지 참고해서 그리드의 칼럼을 추가하고 삭제하면 좋을 꺼 같아요.
- 회원 상태 정상, 휴면, 탈퇴 같은 상태도 추가되면 좋을 듯 합니다!

**Comment by kyd-master** [comment]
- 5건씩 보기 select하는 부분은 표 오른쪽 상단에 두는건 어떨까요~?
