### ISSUE TITLE
관리자 - 대시보드

### ISSUE THREAD

**Issue by MinJeung-Kim** [MinJeung-Kim/Team-Project#12]
# **1차 대시보드 디자인**

<br/>
<p align="center">
	<img src="https://user-images.githubusercontent.com/79193369/111024146-5ed88480-8420-11eb-856d-fe506a5fab9e.png" width="50%" height="50%"/>
</p> 

- [x] 주문 현황 판 생성 
- 주문관리 페이지와 연결되어 숫자가 증가,감소 예정
- [x] 차트 생성
- 한눈에 볼 수 있게 막대차트 2-3개로 수정
- [ ] footer 삭제
- [ ] header 삭제 
- 나이키 로고 제외하고 오른쪽 메뉴 관리자 접속 시간으로 변경

**Comment by tiaz0128** [comment]
> 나이키 로고 제외하고 오른쪽 메뉴 관리자 접속 시간으로 변경
- 세션 시간 옆에는 바로 로그인/로그아웃 할 수 있게 로그인/로그아웃도 추가해주세요!

**Comment by kyd-master** [comment]
왼쪽 메뉴 상단에 관리자 이름같은 간단한 프로필이 나오는거도 좋을 것 같아요~!
