### ISSUE TITLE
grid 오픈 소스 라이브러리 사용

### ISSUE THREAD

**Issue by MinJeung-Kim** [MinJeung-Kim/Team-Project#13]
# 관리자 주문관리 페이지 일부 Grid 오픈소스 사용 

- 실제 회사에서는 **개발 시간 단축, 편리성** 등의 이유로 오픈소스를 사용하고 있습니다.
- 순수 html,css로 구현해 보는 것도 좋지만, 이미 사용자UI에서 충분히 사용해 봤으니 **관리자UI에서는 오픈소스를 사용**해보도록 하겠습니다.

<br/>

![관리자UI-주문관리_1](https://user-images.githubusercontent.com/79193369/111026750-56d41100-842f-11eb-8cb0-a2f0b7d1dcb1.png)

<br/>

# Grid 오픈소스 비교

<br/>

### 1. [Grid.js](https://gridjs.io/docs/examples/server) 
- [Grid.js - git star](https://github.com/grid-js/gridjs) 
![image](https://user-images.githubusercontent.com/79193369/111027162-d19e2b80-8431-11eb-8a7d-ac9ba7f461d0.png)

- [Grid.js - npm 다운로드 수](https://www.npmjs.com/package/gridjs) 
![image](https://user-images.githubusercontent.com/79193369/111027356-1c6c7300-8433-11eb-9f69-60377f6bced1.png)

- 최근 Hot한 typescript기반이며, JS 3대 프레임워크(React, Angular, Vue)에서 무리 없이 사용할 수 있다.

-  Promise 비동기 방식을 사용해서, 클라우드 서버와 연결할 수 있는 기능까지 제공한다.

<br/>

# 실제 사용 후 비교
**1) 간단한 링크 추가**
```html
<script src="https://unpkg.com/gridjs/dist/gridjs.production.min.js"></script>
<script src="https://unpkg.com/gridjs-selection/dist/gridjs-selection.production.min.js"></script>
```
<br/>

**2) 사용자 함수 구현으로 커스터마이징 가능**
```javascript
new gridjs.Grid({
  columns: [
    {
      id: 'awesomeCheckbox',
      name: 'Select',
      plugin: {
        component: gridjs.selection.RowSelection,
        props: {
          id: (row) => row.cell(2).data,
        },
      },
    },
    '주문일(결제일)',
    '주문번호(주문자)',
    '운송장정보(송장번호)',
    '배송비',
    '상품명/옵션',
    '수량',
    '판매가(상품구매금액)',
    {
      name: '총 금액',
      data: null,
      formatter: (_, row) =>
        `$${(row.cells[4].data + row.cells[7].data).toLocaleString()} 원`,
    },
  ],
  pagination: {
    //페이징 처리
    limit: 3,
  },
  search: true, //검색
  fixedHeader: true,
  data: [
    [
      '2021-03-11 10:06:30',
      '20210311-00000031 (김민정)',
      '우체국택배 (123123)',
      2500,
      '나이키 머큐리얼 드림 스피드 슈퍼플라이 8 아카데미 TF 스타일 : CV8122-700 사이즈 : 250 수량 : 1',
      '1',
      149000,
      Array(10)
        .fill()
        .map((x) => [
          Math.round(Math.random() * 100000),
          Math.round(Math.random() * 100000),
        ]),
    ], 
  ],
}).render(document.getElementById('wrapper'));
``` 
<img width="692" alt="pCOsWglOfu" src="https://user-images.githubusercontent.com/79193369/111800664-87281d80-890f-11eb-90dd-40ac5b4820a8.png">

<hr>

### 2. [NHN Cloud UI Grid](https://docs.toast.com/ko/Open%20Source/ToastUI%20Grid/ko/opensource-guide/)
- [NHN Cloud - git star](https://github.com/nhn/tui.grid/releases)
![image](https://user-images.githubusercontent.com/79193369/111027141-b0d5d600-8431-11eb-931f-8708d2732186.png)

-  [NHN Cloud - npm 다운로드 수](https://www.npmjs.com/package/tui-grid) 
![image](https://user-images.githubusercontent.com/79193369/111027327-eaf3a780-8432-11eb-9fbe-0b39039b18e3.png)

<br/>

### ✨**다른 오픈소스도 찾아보시고 위의 오픈소스 보다 더 나은 이유와 함께 적어주세요!**

<br/>

**Comment by sypark132** [comment]
와!! 시간이 정말 많이 단축될 것 같아요!
Grid.js가 깔끔하고 한눈에 보기 좋게 되어있네요~

**Comment by bom318** [comment]
오 좋아요!! 저는 __NHN__ 이 우리가 디자인했던 관리자 페이지와 더 잘 맞을것 같아요!

**Comment by MinJeung-Kim** [comment]
음.. 저는 우선 Grid.js가 디자인 적으로 좀 더 마음이 가고, NHN은 Grid.js보다 쓰기는 쉽다는 생각이 들었어요 !
우리가 회사를 들어가게 되면 그 회사에서 쓰는 오픈소스를 쓰게 될 테니 시간이 되면 둘 다 경험해보는 것도 좋을 것 같지만
아무래도 **다운로드 수**가 더 높고 우리가 자바스크립트를 쓰는 만큼 나중에 **구조화할때 리액트로 변경 할 수도있으니 Grid.js를 사용**하면 좋을 것 같아요 !

**Comment by kyd-master** [comment]
오오  좋아요!! css로 할때보다 시간이 훨씬 단축 될거같아여
저는 NHN보다 Grid.js가 오픈소스 사용자들이 더 보기 편리하고 보기 쉽게 해 놓은것 같아서 
Grid.js를 사용해보고 싶네요 :)

**Comment by tiaz0128** [comment]
- 프로젝트에서 모든 부분을 전부 다 직접 구현하는 것도 좋은 경험이지만
- 오픈소스를 잘 찾아보고 공식문서를 보고 사용하는 것도 매우 중요한 경험이고 능력입니다!
- 다른 의견을 잘 조율해서 한가지를 선택해서 다같이 사용하면서 경험을 쌓아 보시길 바랍니다! 😊

**Comment by MinJeung-Kim** [comment]
# **팀원들의 의견에 따라 Grid.js를 사용하도록 하겠습니다 !!!☺**

**Comment by MinJeung-Kim** [comment]
## Grid.js 확정
