### ISSUE TITLE
게시판 작성 페이지 디자인입니다

### ISSUE THREAD

**Issue by bom318** [MinJeung-Kim/Team-Project#16]
![Group 4](https://user-images.githubusercontent.com/79883826/111062257-1d60db80-84eb-11eb-90e4-17810dac10f5.png)

로그인창과 같이 모달창으로 디자인 해보았습니다!
부족한 부분 말씀해주시면 수정 후 구현 들어가겠습니다!

**Comment by kyd-master** [comment]
관리자가 게시판을 작성하게 될때는 제목 위에 체크박스로 공지사항 등록하기 를 넣어보는거도 괜찮을 거 같아요!
제 의견에 다른분들은 어떻게 생각하세요~?
상품 만족도 별 주는거는 select창 말고 클릭해서 주는걸로 바꾸는 건 어떨까요?  👍

**Comment by tiaz0128** [comment]
- 처음 리뷰를 작성할때 상품을 선택해서 리뷰를 작성하는지 궁금합니다.
- 만약 선택해서 리뷰하는 식이라면 지금 팝업 창에서 어떤 상품인지 알수 있는 정보도 표시 해주면 좋을듯 합니다!

**Comment by MinJeung-Kim** [comment]
> 관리자가 게시판을 작성하게 될때는 제목 위에 체크박스로 공지사항 등록하기 를 넣어보는거도 괜찮을 거 같아요!
> 제 의견에 다른분들은 어떻게 생각하세요~?
> 상품 만족도 별 주는거는 select창 말고 클릭해서 주는걸로 바꾸는 건 어떨까요? 👍

1. 이건 **사용자UI 리뷰**라서 **공지사항을 등록하는건 관리자UI에서 게시판관리**에 있으면 좋을 것 같아요 ~!
2. 별점은 클릭해서 주는 방식에 동의합니다🤞

**Comment by sypark132** [comment]
미리보기도 있으면 좋을 것 같아요!! 파일 첨부했을 때 유용할 듯 싶습니다

**Comment by bom318** [comment]
![게시판작성](https://user-images.githubusercontent.com/79883826/111245815-90cc2f80-8648-11eb-9a0e-8849e3ae32b0.png)

- [x] 상품만족도 변경
- [x] 현재 상품 표시
- [ ] 미리보기 버튼 생성

***

-미리보기 버튼을 만들게되면 미리보기 창도 추가되는건가요?
