### ISSUE TITLE
관리자-상품등록

### ISSUE THREAD

**Issue by kyd-master** [MinJeung-Kim/Team-Project#17]
### 관리자- 상품 등록 수정 디자인입니다.
> 상품등록을 하지 않았을 경우
<p align="center">
	<img src="https://user-images.githubusercontent.com/79883904/111252640-ead2f200-8654-11eb-8455-f5b637988030.png" width="50%" height="50%"/>
</p>

> 상품등록을 했을 경우
<p align="center">
	<img src="https://user-images.githubusercontent.com/79883904/111253039-c7f50d80-8655-11eb-84c5-0e411a3b5028.png" width="50%" height="50%"/>
</p>

- [x] 상품 등록 리스트
- [x] 상품 검색 : 상품명과 상품코드로 select 후 검색해서 상품 찾기
- [x] 그리드 안에 체크박스를 눌렀을 때 전체가 체크 될 수 있게 구현
- [x]  상품리뷰 클릭시 해당 상품의 리뷰페이지로 이동 할 수 있게 링크를 걸어둘 것
- [x] 전체수량, 재고량 필드 추가 예정
- [x] 품절은수량을 체크하여 0이면 자동으로 품절이라고 뜰 수 있게 구현할 예정
- [ ] 차후에 상품등록 구현 완료 후 품절된 상품 체크해서 품절 상품 리스트를 따로 구분할 생각  
- [ ] 관리에 수정버튼 눌렀을 시 모달창 뜨게해서 상품 정보 수정이 가능하도록 구현할 예정

**Comment by tiaz0128** [comment]
- 상품의 전체 수량이 몇개인지 있어야 할꺼 같아요!
- 예를 들어서 신발이 1000개 생산됐는데 주문이 2000개를 들어오면 문제가 될 수 있으니
- 전체 수량이 몇개인지, 현재 주문되고 남은 재고는 몇개인지 표시 할 수 있으면 좋을 듯 합니다!

**Comment by MinJeung-Kim** [comment]
1. 상품찾기, 상품코드는 ```select```박스를 활용하면 좋을 것 같아요.
2. 품절은 체크박스로 하기보단, 수량을 체크하여 0이면 자동으로 ```품절```이라고 뜰 수 있게 구현하면 좋을 것 같아요!
3. 판매항목은 어떤걸 체크하는 건가요 ~?
4. ```전체선택```버튼이 따로 있기보단 그리드 안에 체크박스를 눌렀을 때 전체가 체크 될 수 있게  구현하는게 더 좋을 것 같네요 ~

**Comment by kyd-master** [comment]
@MinJeung-Kim 
1. 네! 상품코드와 상품명으로 검색하는 상품 찾기는 select 박스 활용하려고 합니다!
2. 넵! 참고하겠습니다 👍 
3. 판매항목은 상품중에서 첫 등록은 되어 있지만 판매하고 있지않은 상품들도 있지 않을까해서 넣어봤습니다.
4.  아 그렇네요~~ 따로 버튼이 있는거보다 보기 편할 거 같아요 감사합니다~~

**Comment by kyd-master** [comment]
@tiaz0128 
넵! 상품 전체 수량 꼭 필요한 필드네요! 추가하도록 하겠습니당~~

**Comment by sypark132** [comment]
몇 개씩 볼건지 고르는 select 박스도 있으면 편리할 것 같아요~
