### ISSUE TITLE
관리자 - 주문관리

### ISSUE THREAD

**Issue by MinJeung-Kim** [MinJeung-Kim/Team-Project#19]
# **1차 주문관리 디자인**

<br/>
<p align="center">
	<img src="https://user-images.githubusercontent.com/79193369/111069589-206ec280-8511-11eb-9349-889b4b767155.png" width="50%" height="50%"/>
</p> 

- [x] 주문 상태 메뉴
- 주문상태 :  입금전, 배송준비중, 배송대기, 배송중, 배송완료
- [ ] 클릭하면 각 메뉴에 맞는 그리드 변경
- [x] 그리드 (Grid.js 오픈소스 사용)
- 오픈소스를 사용하여 구현
- [ ] footer 삭제
- [ ] header 삭제

**Comment by sypark132** [comment]
주문자의 주문 정보(받는 사람, 전화번호, 주소 등)도 볼 수 있으면 좋을 것 같아요!

**Comment by MinJeung-Kim** [comment]
오.. 좋은 의견입니다. 적당한 부분에 추가 구현 하겠습니다 !👍

**Comment by kyd-master** [comment]
검색어에 +버튼은 어떤 기능을 하는 건가요~?

**Comment by MinJeung-Kim** [comment]
검색어 박스가 밑에 한 개 더 생기면서 다중 검색이 가능한 기능 입니다 ~!
