### ISSUE TITLE
자바스크립트 기본

### ISSUE THREAD

**Issue by sypark132** [MinJeung-Kim/Team-Project#26]
제가 공부하려고 정리해둔건데 중요한 내용이라 공유합니다! 화이팅😊
부족하거나 잘못된 정보는 알려주시면 수정하겠습니다😄

## use strict 와 Variables

> ## 'use strict';
use strict는 자바스크립트의 비상식적인 행동을 잡아주는 역할이며 **js파일의 맨 위쪽에서 정의**한다.

예를 들어 
자바스크립트에서는 변수의 선언 없이 바로 값을 할당하는 것이 가능하다.
use strict는 이런 것을 오류로 감지하고 우리에게 알려준다.

<img width="60%" height="50%" alt="11" src="https://user-images.githubusercontent.com/79883783/111294545-c9dac300-868d-11eb-8040-9f6998611865.PNG">

> ## 변수(variables)

### 1. < let >
let은 ES6부터 사용되는 변수이다.
+ block level scope이며 block 안에서 let 변수를 정의하면 block 안에서만 사용 가능!
*block은 { }로 묶인 공간을 의미한다
+ block 밖에서 전역변수로서 선언도 가능하지만 함수나 반복문에서처럼 필요한 부분에만 사용하는 게 좋음!
+ 변수로 저장된 데이터 값을 변경할 수 있다. 

<img width="60%" height="60%" alt="1231" src="https://user-images.githubusercontent.com/79883783/111293800-03f79500-868d-11eb-9ef9-cd47866106c1.PNG">

### 2. < const >
const 역시 ES6부터 사용하는 변수이다.
+ let과 같은 block level scope이다.
+ 한 번 정의하면 값을 변경할 수 없다!!

<img width="60%" height="60%" alt="5555" src="https://user-images.githubusercontent.com/79883783/111294241-749eb180-868d-11eb-9ece-bf246ef1010e.PNG">

####  ❌ 쓰지 말 것 ❌
+ var는 전역변수로 block 안에서 정의된 변수가 block 밖에서도 사용 가능하고 어디에서나! 사용 가능하기 때문에
변수호출 뒤에 변수를 선언해도 정상적으로 작동되는 이상한 현상이 발생함.
+ 값을 여러 번 할당 가능하기 때문에 동일한 변수명을 쓸 경우 에러가 발생하기 쉽다.

<img width="60%" height="60%" alt="3333" src="https://user-images.githubusercontent.com/79883783/111294301-84b69100-868d-11eb-991a-ed42a4216926.PNG">

### 4. < hoisting >
위에서 말한 이상한 현상을 호이스팅이라고 하는데 정확히 말하면
**변수의 선언 위치와 상관 없이 맨 위에 선언된 것처럼 실행되는 현상**이다.
면접에서도 많이 물어본다고 하니 알아두면 좋음!

참고 영상
[유투브 드림코딩 by 엘리](https://www.youtube.com/watch?v=OCCpGh4ujb8&list=PLv2d7VI9OotTVOL4QmPfvJWPJvkmv6h-2&index=3)

**Comment by tiaz0128** [comment]
좋은 내용입니다! 이슈나 PR 에 공부한 내용 공유해주셔서 감사합니다!
PR이나 이슈는 찾아보기 힘들기 때문에  따로 꼭 정리해두실 바랍니다! 저는 노션을 추천해드립니다! 

참고영상 링크가 이상한데 아래의 형태로 해주시면 제대로 들어갑니다!

```
(유투브 드림코딩 by 엘리)[영상 주소 url]
```

**Comment by sypark132** [comment]
@tiaz0128  감사합니다! 저는 링크가 왜 안될까요ㅠㅠ?

**Comment by tiaz0128** [comment]
ㅋㅋ 제가 반대로 공유했네요!

```
[유투브 드림코딩 by 엘리](영상 주소)
```

**Comment by sypark132** [comment]
> ㅋㅋ 제가 반대로 공유했네요!
> 
> ```
> [유투브 드림코딩 by 엘리](영상 주소)
> ```

오! 됐습니다 감사합니다😀

**Comment by kyd-master** [comment]
참고해서 공부 열심히 해볼게요~~ 서윤님 감사해용 😊

**Comment by bom318** [comment]
저도 열심히 공부하겠습니다! 감사합니다~~
