### ISSUE TITLE
회원 상세보기 모달창 디자인

### ISSUE THREAD

**Issue by sypark132** [MinJeung-Kim/Team-Project#27]
![Group 1](https://user-images.githubusercontent.com/79883783/111400488-c6d1e800-870a-11eb-8e1e-ac15167dc5ed.png)

+ 우편번호 찾기, 메모 추가했습니다.
추후에 db테이블에도 추가하겠습니다!

- [ ] 성별칸
- [ ] 다시쓰기, 저장

**Comment by tiaz0128** [comment]
## 관련된 화면 링크
- 팝업창은 특정한 화면에 의존하기 때문에 어떤 화면에 있는지 링크를 걸어주면 좀더 보기가 좋을 듯 합니다.
- 관리자-회원관리 디자인 #11 링크를 넣어서 어떤화면과 연결되는지 한눈에 볼수 있어서 좋을 듯 합니다.
- PR 과 이슈는 각각 고유한 번호가 붙으니 그것을 활용하면 좋을듯 합니다!

```
#PR번호
#이슈변호
```

## 우편번호 API
- 우편번호는 카카오나 네이버의 주소를 찾을수 있는 API 가 있을꺼 같습니다. 
- 한번 찾아보고 구현 할때 적용 가능할지 찾아보시고 염두해두면 좋을듯합니다!
- [API란? by 드림코딩 엘리](https://www.youtube.com/watch?v=ogT267HvNuQ)

**Comment by MinJeung-Kim** [comment]
DB테이블 설계 추가 시, 
이슈 - Nike ERP 공유(#25)에 업데이트 해주세요 ~❗❗
