### ISSUE TITLE
오늘 날짜 세팅 공용 코드

### ISSUE THREAD

**Issue by MinJeung-Kim** [MinJeung-Kim/Team-Project#45]
### ```common-dateSetting.js```

```javascript
const dateEnd = document.querySelector('.date-end');
const dateStart = document.querySelector('.date-start');

let date = new Date();
let beforeMonth = new Date(Date.parse(date) - 30 * 1000 * 60 * 60 * 22); //30일전

dateStart.value = beforeMonth.toISOString().substring(0, 10);
dateEnd.value = date.toISOString().substring(0, 10); // today
```

**Comment by tiaz0128** [comment]
## 공통코드라는 것에 대해서
- 공통코드는 말 그대로 모두가 사용하게 될 가능성이 높은 코드를 말합니다.
- 여기서 록시님이 작성한 `common-dateSetting.js` 을 공통코드 라고 보기에는 어렵습니다.
- 왜냐하면 특정한 기능이 따로 함수로 만들어 놓은게 아니라 화면의 전체적인 코딩을 해놓은 파일이기 떄문입니다.

<br/>

## 어떤 부분을 공통으로 만들어야 하지?
- 여기서 공통 코드로 뽑아 낼수 있는 부분은 오늘로부터 특정날짜 이전 이후를 구하는 코드라고 생각합니다.
- 그러면 이부분을 다른 사람도 쓸수 있게 따로 함수형태로 만들어두면 다른 사람도 날짜를 구할때 해당 함수를 쓰면되겠죠!
- 이런것을 공통코드, 공통함수 등이라 합니다!
- 다시 위의 파일에서 공통코드를 뽑아내서 다른 사람들이 쓸수 있게 만들어보세요!

```js
new Date(Date.parse(date) - 30 * 1000 * 60 * 60 * 22); //30일전
```

**Comment by MinJeung-Kim** [comment]
## 멘토님의 조언을 받아 공통코드를 수정했습니다 !
## PR #49 참고해주세요 ~!
