### ISSUE TITLE
[사용자] 상품상세페이지 - 사이즈선택영역

### ISSUE THREAD

**Issue by kyd-master** [MinJeung-Kim/Team-Project#53]
### 구현목표
- [x]  현재는 사이즈 여러개 선택되므로 사이즈 두개 이상 클릭될 수 없게 

### 질문사항

- [x] 사이즈가 하나만 선택되게 하는건 조건문으로도 가능한가요?

**Comment by tiaz0128** [comment]
어디까지 구현했는지 PR로 남겨주시면 코드를 보고 알려드리곘습니다! 😀

**Comment by kyd-master** [comment]
제가 rgb색상코드 참고를 잘못해서 색상을 잘못 선택한거 같아요! 다시 수정했습니다!
